In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv("./NRC-VAD-Lexicon.csv")
df.head()

       word      v      a      d
0  aaaaaaah  0.479  0.606  0.291
1     aaaah  0.520  0.636  0.282
2  aardvark  0.427  0.490  0.437
3     aback  0.385  0.407  0.288
4    abacus  0.510  0.276  0.485

In [21]:
df_ge = pd.read_csv("../goemotions.csv", index_col=0)
labels = df_ge.columns[2:]
labels

Index(['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring',
       'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval',
       'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief',
       'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization',
       'relief', 'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

In [24]:
df_lite = df[df["word"].isin(labels)]
df_lite

                 word      v      a      d
251        admiration  0.969  0.583  0.726
624         amusement  0.929  0.837  0.803
670             anger  0.167  0.865  0.657
709         annoyance  0.167  0.718  0.342
865          approval  0.854  0.460  0.889
2575           caring  0.635  0.469  0.500
3617        confusion  0.255  0.667  0.277
4255        curiosity  0.750  0.755  0.463
4737           desire  0.896  0.692  0.647
4983   disappointment  0.115  0.490  0.336
4984      disapproval  0.085  0.551  0.367
5067          disgust  0.052  0.775  0.317
5772    embarrassment  0.143  0.685  0.226
6200       excitement  0.896  0.684  0.731
6546             fear  0.073  0.840  0.293
7742        gratitude  0.885  0.441  0.610
7799            grief  0.070  0.640  0.474
9715              joy  0.980  0.824  0.794
10455            love  1.000  0.519  0.673
11689     nervousness  0.163  0.915  0.241
11712         neutral  0.469  0.184  0.357
12181        optimism  0.949  0.565  0.814
13611           pride  0.729  0.634  0.848
14286     realization  0.554  0.510  0.836
14603          relief  0.844  0.278  0.481
14647         remorse  0.103  0.673  0.377
15242         sadness  0.052  0.288  0.164
17368        surprise  0.875  0.875  0.562

In [25]:
for col in "vad":
    x = df_lite[col].values
    df_lite[col] = np.interp(x, (0, 1), (-1, 1))

df_lite

/tmp/ipykernel_15689/1289133602.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lite[col] = np.interp(x, (0, 1), (-1, 1))

                 word      v      a      d
251        admiration  0.938  0.166  0.452
624         amusement  0.858  0.674  0.606
670             anger -0.666  0.730  0.314
709         annoyance -0.666  0.436 -0.316
865          approval  0.708 -0.080  0.778
2575           caring  0.270 -0.062  0.000
3617        confusion -0.490  0.334 -0.446
4255        curiosity  0.500  0.510 -0.074
4737           desire  0.792  0.384  0.294
4983   disappointment -0.770 -0.020 -0.328
4984      disapproval -0.830  0.102 -0.266
5067          disgust -0.896  0.550 -0.366
5772    embarrassment -0.714  0.370 -0.548
6200       excitement  0.792  0.368  0.462
6546             fear -0.854  0.680 -0.414
7742        gratitude  0.770 -0.118  0.220
7799            grief -0.860  0.280 -0.052
9715              joy  0.960  0.648  0.588
10455            love  1.000  0.038  0.346
11689     nervousness -0.674  0.830 -0.518
11712         neutral -0.062 -0.632 -0.286
12181        optimism  0.898  0.130  0.628
13611           pride  0.458  0.268  0.696
14286     realization  0.108  0.020  0.672
14603          relief  0.688 -0.444 -0.038
14647         remorse -0.794  0.346 -0.246
15242         sadness -0.896 -0.424 -0.672
17368        surprise  0.750  0.750  0.124

In [26]:
df_lite.to_csv("./goemotions_points.csv")

In [32]:
labels = ["anger", "fear", "joy", "surprise", "sadness", "love"]

In [33]:
df_lite = df[df["word"].isin(labels)]
df_lite

           word      v      a      d
670       anger  0.167  0.865  0.657
6546       fear  0.073  0.840  0.293
9715        joy  0.980  0.824  0.794
10455      love  1.000  0.519  0.673
15242   sadness  0.052  0.288  0.164
17368  surprise  0.875  0.875  0.562

In [34]:
for col in "vad":
    x = df_lite[col].values
    df_lite[col] = np.interp(x, (0, 1), (-1, 1))

df_lite

/tmp/ipykernel_15689/1289133602.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lite[col] = np.interp(x, (0, 1), (-1, 1))

           word      v      a      d
670       anger -0.666  0.730  0.314
6546       fear -0.854  0.680 -0.414
9715        joy  0.960  0.648  0.588
10455      love  1.000  0.038  0.346
15242   sadness -0.896 -0.424 -0.672
17368  surprise  0.750  0.750  0.124

In [ ]:
df_lite.to_csv("./carer_points.csv")